---
parser: babel-eslint
parserOptions:
  ecmaVersion: 6
  sourceType: module
  ecmaFeatures:
    experimentalObjectRestSpread: true
env:
  browser: true
  node: true
  amd: true
  commonjs: true
  jquery: true
  es6: true
rules:
  curly: [2, all]
  keyword-spacing: [2, {}]
  no-with: 2
  brace-style: [2, 1tbs, {allowSingleLine: true}]
  no-multi-spaces: 2
  space-unary-ops: [2, {words: false, nonwords: false}]
  space-infix-ops: 2
  one-var: 0
  space-in-parens:
  - 2
  - never
  no-empty:
  - 2
  - allowEmptyCatch: true
  wrap-iife: 1
  space-before-function-paren:
  - 2
  - anonymous: always
    named: never
  comma-style:
  - 2
  - last
  quotes:
  - 2
  - single
  - allowTemplateLiterals: true
  no-multi-str: 2
  no-implicit-coercion:
  - 2
  - boolean: true
    string: true
    number: true
  yoda:
  - 2
  - never
  array-bracket-spacing:
  - 2
  - never
  key-spacing:
  - 2
  - beforeColon: false
    afterColon: true
  quote-props:
  - 2
  - as-needed
  spaced-comment: 0
  eol-last: 2
  no-multiple-empty-lines: 2
  no-mixed-spaces-and-tabs: 2
  no-trailing-spaces: 2
  linebreak-style: 0
  indent: [1, tab, {SwitchCase: 1}]
  semi:
  - 2
  - always
  no-extra-semi: 2
  no-unused-vars: 2
  no-undef: 2
  new-cap:
  - 2
  - capIsNewExceptions:
    - Boolean
    - String
    - Number
    - Velocity
    - MD5
    - Snap
    - ObjectId
  no-delete-var: 2
globals:
  mina: true
  Snap: true
  requireSchemes: true
  getSvgPaths: true
  getSvgElement: true
  localize: true
