---
- title: Chacarera Simple
  scheme: chacarera
  titleRu: Чакарера симпле
- title: Chacarera Doble
  scheme: chacarera_doble
  titleRu: Чакарера добле
- title: Zamba
  scheme: zamba
  titleRu: Самба
- title: Zamba Alegre
  scheme: zamba_alegre
  titleRu: Самба алегре
- title: Gato
  scheme: gato
  titleRu: Гато
- title: Gato Cuyano
  scheme: gato_cuyano
  titleRu: Гато кужано
- title: Caramba
  scheme: caramba
  titleRu: Карамба
- title: Bailecito
  scheme: bailecito
  titleRu: Байлесито
- title: Escondido
  scheme: escondido
  titleRu: Эскондидо
- title: Remedio Norteño
  scheme: remedio
  titleRu: Ремедио нортеньо
- title: Remedio Atamisqueño
  scheme: remedio_atamisqueno
  titleRu: Ремедио атамискеньо
- title: Huayra Muyoj
  scheme: huayra_muyoj
  titleRu: Уайра мужох
- title: Huella
  scheme: huella
  titleRu: Уэжа
- title: Arunguita
  scheme: arunguita
  titleRu: Арунгита
